# -*- encoding:utf-8 -*-

# PRODUCTION SETTINGS
# OVERWRITE BY DEV|TEST


from private import *


DEBUG = False

MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = ''
MAIL_PASSWORD = ''

SECURITY_POST_LOGIN_VIEW = '/profile'
SECURITY_PASSWORD_HASH = 'plaintext'
SECURITY_PASSWORD_SALT = 'password_salt'
SECURITY_REMEMBER_SALT = 'remember_salt'
SECURITY_RESET_SALT = 'reset_salt'
SECURITY_RESET_WITHIN = '5 days'
SECURITY_CONFIRM_WITHIN = '5 days'
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_TRACKABLE = True

CSRF_ENABLED = True

DEBUG_TB_INTERCEPT_REDIRECTS = False

ASSETS_DEBUG = False